### ISSUE TITLE
Probable Error Report in "oslots.tf"

### ISSUE THREAD

**Issue by kungsik** [ETCBC/text-fabric-data#4]
Hello.  

Recently, I'm developing the Bible Web Application for the Korean readers, and this is already in service (http://app.alphalef.com). The source code appears in my Github repository. I'm so appreciate you to permit the public use of this valuable database. 

The following code is to show the each chapter of Hebrew text.

```
@app.route('/text/')
@app.route('/text/<book>')
@app.route('/text/<book>/<int:chapter>')
def text_page(book='Genesis', chapter=1):
    chpNode = T.nodeFromSection((book, chapter))
    verseNode = L.d(chpNode, otype='verse')
    whole_chpNode = T.nodeFromSection((book,))
    last_chp = T.sectionFromNode(whole_chpNode, lastSlot=True)
    verse = ""
    for v in verseNode:
        verse += '<span class=verseNode><a class=verse_num id=verse_num verse_node='+str(v)+'>'
        verse += str(T.sectionFromNode(v)[2])
        verse += ' </a>'
        clauseNode = L.d(v, otype='clause')
        for c in clauseNode:
            verse += '<span class=clauseNode id=clauseNode clause_node='+str(c)+'>'
            verse += "<span class='syntax clause1 hidden' id=syntax>C:"+ kb.eng_to_kor(F.typ.v(c), 'abbr') +"</span>"
            phraseNode = L.d(c, otype='phrase')
            for p in phraseNode:
                verse += '<span class=phraseNode id=phraseNode phrase_node='+str(p)+'>'
                verse += "<span class='syntax phrase1 hidden' id=syntax>P:"+ kb.eng_to_kor(F.typ.v(p), 'abbr') + "," + kb.eng_to_kor(F.function.v(p), 'abbr') + "</span>"
                wordsNode = L.d(p, otype='word')
                for w in wordsNode:
                    verse += '<span class=wordNode><a tabindex=0 class=word_elm data-poload=/api/word/'+str(w)+' data-toggle=popover data-trigger=focus>'
                    verse += F.g_word_utf8.v(w)
                    verse += '</a></span>'
                    if F.trailer_utf8.v(w):
                        verse += '<span class=trailerNode>'
                        verse += F.trailer_utf8.v(w)
                        verse += '</span>'
                verse += '</span>'
            verse += '</span>'
        verse += '</span>'
    return render_template('text.html', verse=verse, book=book, chapter=chapter, last_chp=last_chp[1])
```
This code works very well. However, I found the probable error in Esther 4:16. Because this verse is crucial verse in my doctoral dissertation in process, this drew my attention. The last part of Esth. 4:16 appears as follows:

## >  לֹֽא־כַדָּ֔ת וְאָבָֽדְתִּי׃ כַאֲשֶׁ֥ר אָבַ֖דְתִּי 

So I opened the "oslots.tf", and found the following lines. 

Line 77919: 367523,367527
Line 77920: 367524-367526

It seems that each slot number corresponds to each word as follows:

367523 ו
367527 אבדתי
367524 כ
367525 אשר
367526 אבדתי

Thus, it seems that the word order is not correct. Although I do not understand fully the data structure of the Text-Fabric, it seems that the each line refers to the clause unit. So I made a correction as follows:

Line 77919: 367523-367526 (WxQ0) וכאשר אבדתי
Line 77920: 367527 (xQt0) אבדתי

After the correction, it works very well in my application. 
Please check this issue. 

Thanks.

**Comment by dirkroorda** [comment]
I think it is crucial to understand the data structure of text-fabric. See https://github.com/ETCBC/text-fabric/wiki/Data-model and especially https://github.com/ETCBC/text-fabric/wiki/File-formats and also https://github.com/ETCBC/text-fabric/wiki/Optimizations.
The oslots.tf is an edge-feature file in that it defines a set of edges between nodes. In particular, oslots states which word nodes are contained in which non-word nodes.
So line
```367523,367527```
states that the node that corresponds to that line contains two words, namely `367523` and `367527`.
Lets find out which node this is. Basically, you need a program to do that. Look at the beginning of the file. There you see the lines: ```
426582	1-11
12-18
```
The first line means that node `426582` contains words `1` to `11` (including).
The next line means that node `426583` contains words `12` to `18`.

So the line you mention (77919) is the 77913 line after line 6 which is about node 426582. So your line is about node 426582+77913 = 504495. Looking in otype.tf we see that this is a clause.
Apparently, this is a clause with a gap.

I think you stumbled on the fact that not every Hebrew sentence is the concatenation of all the clauses it contains.

As regards to your question about licensing: yes, the database is open to the public (non-commercial), as the license states here: https://etcbc.github.io/text-fabric-data/features/hebrew/etcbc4c/0_home.html

I hope this helps.

**Comment by kungsik** [comment]
Many thanks for your kind and detailed answer. 
I just realized I misunderstood the syntactic issue of Esth. 4:16. 
I have to update my code!

Thanks!!

**Comment by kungsik** [comment]
I realized that I did very silly mistake, and that mistake was so big issue!! 
I updated the code and now it works very well. Many thanks for your helpful answer.
Someone may do same mistake. So I want to leave this issue. 

![image](https://lh3.googleusercontent.com/R4vdunxFwJHXk6JVRvb28KSYIjrk3qe8UDQ9ylyPCSzkfrPgIgUx8227l8CQvd4gp7-vUCiziCCBGqqcLVYfIr0kvvJUqr8bgdBUGfmeKzAgq59FZCl3le2ZXw1DIWT4Fn2t3tycweY4tmVzLPhTry5LDWFHBtaE1xuThxIYE2JLHQNzntJTKob8YwngYSfIM2AAb3E20pwy2o8XoaI0WQMbTfPyeFeeq5fgb1_l0lT5QaLhJeeAeN1-79FpUkZomXMHTq2GEcu2KmmolphUJ6UwWhxy91QgU641xCaEvhHocHtaaIap7UzSKFDLAo76f0tLrTSsC4dF1oTItHK-ggphRIvF9NuvQ58uxi7J38QsIVm2pu5RCVOU2ylD_WSYbsPuyt0WwUsVwKiWG-VIa8vv_E5Xq4qCiHpIT1mGhPNApeAGs8K0b3BhJhIeNbNbZwMXpKLS6WOm818QBFkQN7JiZ6p9MqWHLjCp0mINR0w__ncNHqGzE5IWDBPgP7hMIghGLSXaVPwyOrS_bE4IeyR2owPhgdRK35WKvskocKulEtCvToTnrMutsIHUe0QEv-VdxXqLzy_NVcG5B5dKscbum6yZEDs6psNvG5RMsWbI4pHnAL-OrpAEza-NxpwXwhmaao1t4sILfTdoh5PeNvyWKL6RyKJudBEboYauVA=w741-h135-no)

**Comment by kungsik** [comment]
Hello.


Thanks to your help, I could fix the big problem. 😊

And thanks for inviting me to slack.


Best,



Kim.


________________________________
보낸 사람: Dirk Roorda <notifications@github.com>
보낸 날짜: 2017년 6월 19일 월요일 오후 1:50:34
받는 사람: ETCBC/text-fabric-data
참조: Kyoungsik Kim; Author
제목: Re: [ETCBC/text-fabric-data] Probable Error Report in "oslots.tf" (#4)


I think it is crucial to understand the data structure of text-fabric. See https://github.com/ETCBC/text-fabric/wiki/Data-model and especially https://github.com/ETCBC/text-fabric/wiki/File-formats and also https://github.com/ETCBC/text-fabric/wiki/Optimizations.
The oslots.tf is an edge-feature file in that it defines a set of edges between nodes. In particular, oslots states which word nodes are contained in which non-word nodes.
So line
367523,367527
states that the node that corresponds to that line contains two words, namely 367523 and 367527.
Lets find out which node this is. Basically, you need a program to do that. Look at the beginning of the file. There you see the lines: ```
426582 1-11
12-18

The first line means that node `426582` contains words `1` to `11` (including).
The next line means that node `426583` contains words `12` to `18`.

So the line you mention (77919) is the 77913 line after line 6 which is about node 426582. So your line is about node 426582+77913 = 504495. Looking in otype.tf we see that this is a clause.
Apparently, this is a clause with a gap.

I think you stumbled on the fact that not every Hebrew sentence is the concatenation of all the clauses it contains.

As regards to your question about licensing: yes, the database is open to the public (non-commercial), as the license states here: https://etcbc.github.io/text-fabric-data/features/hebrew/etcbc4c/0_home.html

I hope this helps.
